### ISSUE TITLE
NullablePointer?

### ISSUE THREAD

**Issue by adah1972** [CaseyCarter/cmcstl2#111]
I am wondering whether there is a specific reason why `NullablePointer` is not defined. I think it could be defined more or less as follows:

```cpp
template <class T>
concept bool NullablePointer =
    EqualityComparable<T> &&
    DefaultConstructible<T> &&
    MoveConstructible<T> &&
    Assignable<T&, T&&> &&
    Destructible<T> &&
    requires(T a, T b) {
        { T(nullptr) };
        { a = nullptr };
        { a == nullptr } -> Boolean;
        { a != nullptr } -> Boolean;
        { a == b } -> Boolean;
        { a != b } -> Boolean;
    };
```

Did I miss anything?

**Comment by adah1972** [comment]
Two amendments. `{ a == b } -> Boolean;` seems unnecessary, as it is implied by `EqualityComparable`. The [CppReference.com](http://en.cppreference.com/w/cpp/concept/NullablePointer) page explicitly says "dereferencing (operator* or operator->) is not required of a NullablePointer type", so I am wondering its usefulness now too.

Is there another useful concept to check whether an object behaves like a pointer?

**Comment by CaseyCarter** [comment]
The Ranges TS doesn't define `NullablePointer` because that concept is not necessary to constrain the iterators and algorithms. If I were to do so, I would translate the Standard's requirements as (from N4659 [nullablepointer.requirements]):

> 1 A `NullablePointer` type is a pointer-like type that supports null values. A type `P` meets the requirements of `NullablePointer` if:
>
> (1.1) — `P` satisfies the requirements of `EqualityComparable`, `DefaultConstructible`, `CopyConstructible`, `CopyAssignable`, and `Destructible`,
>
> (1.2) — lvalues of type `P` are swappable (20.5.3.2),

These requirements together as a group are roughly equivalent to `Regular` from the Ranges TS. TS `EqualityComparable` requires `!=`, which Standard `EqualityComparable` does not, but that's ok because Table 28 below is about to add that requirement for `NullablePointer`. TS comparison concepts also require the result to satisfy `Boolean` which is significantly stronger than simply being contextually convertible to `bool`. I don't think this strengthening rules out many real-world models of this `NullablePointer` concept so I'll allow the strengthening and note it here.

> (1.3) — the expressions shown in Table 28 are valid and have the indicated semantics, and
>
> (1.4) — `P` satisfies all the other requirements of this subclause.
>
> 2 A value-initialized object of type `P` produces the null value of the type. The null value shall be equivalent only to itself. A default-initialized object of type `P` may have an indeterminate value. [ *Note:* Operations involving indeterminate values may cause undefined behavior. —*end note*]

This requires `P{}` to be an equality-preserving expression, and requires `P{} == P{}` to be in the domain of `==`.

> 3 An object `p` of type `P` can be contextually converted to `bool` (Clause 7). The effect shall be as if `p != nullptr` had been evaluated in place of `p`.

"Can be contextually converted to bool" is equivalent to the expression requirement `p ? E1 : E2` where `E1` and `E2` are any expressions such that `true ? E1 : E2` is valid. I would probably pick `true` and `false` for `E1` and `E2` just for simplicity and write this as `p ? true : false`. The second sentence is a non-syntactic requirement on values of expressions that requires that `(p ? true : false) == (p != nullptr)`.

> 4 No operation which is part of the `NullablePointer` requirements shall exit via an exception.

"Shall not exit via an exception" is notably *not* the same requirement as "shall be `noexcept`", so this one has no syntactic expression. We'll have to list it equivalently as an axiom of our `NullablePointer` concept.

> 5 In Table 28, `u` denotes an identifier, `t` denotes a non-const lvalue of type `P`, `a` and `b` denote values of type (possibly `const`) `P`, and `np` denotes a value of type (possibly `const`) `std::nullptr_t`.

Table 28 — `NullablePointer` requirements [nullablepointer]

| Row | Expression | Return type | Operational semantics |
| ----  | -----------  | ------------  | ------------------------  |
| 0 | `P u(np);`<br>`P u = np;` | | Postconditions: `u == nullptr` |
| 1 | `P(np)` | | Postconditions: `P(np) == nullptr` |
| 2 | `t = np` | `P&` | Postconditions: `t == nullptr` |
| 3 | `a != b` | contextually convertible to `bool` | `!(a == b)` |
| 4 | `a == np`<br>`np == a` | contextually convertible to `bool` | `a == P()` |
| 5 | `a != np`<br>`np != a` | contextually convertible to `bool` | `!(a == np)` |

Rows 0 and 1 require `Constructible<P, std::nullptr_t>` and `ConvertibleTo<std::nullptr_t, P>` along with the semantic requirement that `P{nullptr} == P{}`. Row 2 is `Assignable<P&, std::nullptr_t>`. Row 3 is the other half of TS `EqualityComparable<P>` as noted above. Row 4 and 5 together are `EqualityComparableWith<P, std::nullptr_t>` with the added semantic requirement that `P{} == nullptr` is `true`.

If I got everything, this would be expressed in the style of the Ranges TS as:

> ```c++
> template<class T>
> concept bool ContextuallyConvertibleToBool = requires(T&& t) {
>   static_cast<T&&>(t) ? true : false;
> };
>
> template<class P>
> concept bool NullablePointer = 
>   Regular<P> &&
>   ContextuallyConvertibleToBool<const P> &&
>   Constructible<P, std::nullptr_t> &&
>   ConvertibleTo<std::nullptr_t, P> &&
>   Assignable<P&, std::nullptr_t> &&
>   EqualityComparableWith<P, std::nullptr_t> &&
>   requires { P{}; };
> ```
>
> Let `p` be a possibly-`const` object of type `P`. `P` satisfies `NullablePointer` if and only if:
> * `P{}` is in the domain of `==` [*Note:* Since `P{}` is equality-preserving, `P{} == P{}` must consequently be `true`.&mdash;*end note*]
> * `P(nullptr) == P{}`
> * `(p ? true : false) == (p != nullptr)`
> * No expression included in these requirements exits via an exception.

**Comment by CaseyCarter** [comment]
> The [CppReference.com](http://en.cppreference.com/w/cpp/concept/NullablePointer) page explicitly says "dereferencing (operator* or operator->) is not required of a `NullablePointer` type", so I am wondering its usefulness now too.
>
> Is there another useful concept to check whether an object behaves like a pointer?

There are certainly iterator concepts that could be usefully applied to require something to "behave like a pointer." The allocator requirements, for example, require an allocator's `pointer` type to satisfy `NullablePointer` and satisfy the requirements of a random access iterator and a contiguous iterator. Really it's a question of exactly which behaviors you consider to be pointer-like for your use case.

**Comment by adah1972** [comment]
Thanks for your fast and detailed answer.

> Really it's a question of exactly which behaviors you consider to be pointer-like for your use case.

A pointer should point to something. So I was thinking about `*` and `->`, especially `*`. (I do not know how to express the `->` concept requirement, actually.)

Your `detail::Dereferenceable` seems pretty close. I am not sure why it is in `std::experimental::ranges::v1::detail` instead of `std::experimental::ranges::v1`.

**Comment by adah1972** [comment]
Checking your implementation again, I have concluded I do not want to use `NullablePointer`. I misunderstood the spec and used `MoveConstructible`, because I think `std::unique_ptr` should satisfy `NullablePointer`. But it does not. I only want a concept to constrain the type to common pointer like types like pointers and smart pointers (`shared_ptr`, `unique_ptr`, etc.).

**Comment by adah1972** [comment]
Question: Should `detail::Dereferenceable` be pulled out of `detail`, as it should be of general interest to users of cmcstl2?

**Comment by ericniebler** [comment]
> Question: Should `detail::Dereferenceable` be pulled out of `detail`, as it should be of general interest to users of cmcstl2?

I don't think this is an interesting concept. It has no associated semantics whatsoever.

**Comment by ericniebler** [comment]
> I only want a concept to constrain the type to common pointer like types like pointers and smart pointers (`shared_ptr`, `unique_ptr`, etc.).

It sounds to me that what you want is `Readable`.

**Comment by adah1972** [comment]
Great. The name `Readable` eluded my notice, but `Readable` and `Writable` are closer to what I need. Thanks.
