### ISSUE TITLE
test/detail/temporary_vector.cpp:28:5: error: static assertion failed

### ISSUE THREAD

**Issue by octoploid** [CaseyCarter/cmcstl2#22]
With gcc trunk:

```
build % CXXFLAGS="-O3" cmake -DCMAKE_CXX_COMPILER=/var/tmp/gcc_test/usr/local/bin/g++ ..
build % make
...
 
/var/tmp/cmcstl2/test/detail/temporary_vector.cpp: In function ‘int main()’:
/var/tmp/cmcstl2/test/detail/temporary_vector.cpp:27:31: warning: requested alignment 256 is larger than 128 [-Wattributes]
     struct alignas(alignment) foo { char c; };
                               ^

/var/tmp/cmcstl2/test/detail/temporary_vector.cpp:28:5: error: static assertion failed
     static_assert(alignof(foo) == alignment);
     ^

test/detail/CMakeFiles/temporary_vector.dir/build.make:62: recipe for target 'test/detail/CMakeFiles/temporary_vector.dir/temporary_vector.cpp.o' failed
make[2]: *** [test/detail/CMakeFiles/temporary_vector.dir/temporary_vector.cpp.o] Error 1
CMakeFiles/Makefile2:1631: recipe for target 'test/detail/CMakeFiles/temporary_vector.dir/all' failed
make[1]: *** [test/detail/CMakeFiles/temporary_vector.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by octoploid** [comment]
I've opened https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68267

**Comment by CaseyCarter** [comment]
Per [basic.align]/3:
> An *extended alignment* is represented by an alignment greater than `alignof(std::max_align_t)`. It is implementation-defined whether any extended alignments are supported and the contexts in which they are supported (7.6.2).

So this is more likely a difference between my development environment and yours than a bug in the compiler.

I used 256 in the `temporary_vector` test because it's the largest alignment supported by g++ in my development environment, not because anything in the library needs an alignment that large. Or any extended alignment, for that matter. The test also makes non-portable assumptions about the conversion of pointer values to integers, which is more easily fixed.

**Comment by CaseyCarter** [comment]
I've changed the test program to not use an alignment larger than 128, although once Concepts are more widely supported I suppose I'll have to come up with some platform-specific configuration and/or pick a small number that is widely applicable.
