### ISSUE TITLE
View Pipe Form: Mixing reverse and filter

### ISSUE THREAD

**Issue by adah1972** [CaseyCarter/cmcstl2#223]
Continuing from #214.

This works:

```cpp
#include <experimental/ranges/algorithm>
#include <experimental/ranges/iterator>
#include <experimental/ranges/ranges>
#include <algorithm>
#include <iostream>
#include <vector>

int main()
{
    namespace ranges = std::experimental::ranges;
    int a[] = {1, 7, 3, 6, 5, 2, 4, 8};
    auto r = a
        | ranges::view::filter([](int i) { return i % 2 == 0; })
        | ranges::view::reverse;
    ranges::copy(a, ranges::ostream_iterator<int>(std::cout, " "));
    std::cout << std::endl;
    ranges::copy(r, ranges::ostream_iterator<int>(std::cout, " "));
    std::cout << std::endl;
}
```

Reversing the two view adapters doesn't. Neither order works if I change the type of `a` from `int [8]` to `std::vector<int>`. All three failure cases have different error messages.

**Comment by CaseyCarter** [comment]
Reduces to:
```c++
#include <experimental/ranges/ranges>

int main() {
    namespace ranges = std::experimental::ranges;
    int a[] = {1, 7, 3, 6, 5, 2, 4, 8};
    auto r0 = ranges::view::reverse(a);
    auto is_even = [](int i) { return i % 2 == 0; };
    auto r1 = ranges::view::filter(r0, is_even);
    int sum = 0;
    for (auto i : r1) {
        sum += i;
    }
    return sum - 20;
}
```

The problem seems to be constraint recursion on the `_ConstructibleFromRange` constraint of `reverse_view`'s converting constructor. It isn't affected by removing the conversion operators from `view_interface`, but *is* corrected by applying a `_NotSameAs<reverse_view>` to the converting constructor anywhere before the `_ConstructibleFromRange` constraint. It's also notably corrected by:

```diff
diff --git a/include/stl2/view/reverse.hpp b/include/stl2/view/reverse.hpp
index 6f70a70..b2f59f1 100644
--- a/include/stl2/view/reverse.hpp
+++ b/include/stl2/view/reverse.hpp
@@ -37,13 +37,9 @@ STL2_OPEN_NAMESPACE {
    public:
        reverse_view() = default;

-       constexpr explicit reverse_view(Rng rng)
-       : base_{std::move(rng)} {}
-
-       template<ViewableRange O>
-       requires BidirectionalRange<O> && _ConstructibleFromRange<Rng, O>
-       constexpr explicit reverse_view(O&& o)
-       : base_(view::all(std::forward<O>(o))) {}
+       template<ConvertibleTo<Rng> T>
+       constexpr explicit reverse_view(T&& t)
+       : base_(Rng(std::forward<T>(t))) {}

        constexpr Rng base() const
        { return base_; }
```
@ericniebler, what do the constraints on the views' converting constructors buy us, other than potential recursion? Why do we care at all about the properties of the constructor argument beyond the fact that we can turn it into a `Rng`? It shouldn't be the adaptors' responsibility to enforce the lifetime model in their converting constructors, it's the responsibility of the underlying `View` type (recall that `Rng` is a `View`, despite the naming - I haven't replaced all the names yet as in the working draft). As long as the adaptors faithfully transmit the type and value category of the initializer I see no need for constraints other than that the conversion will succeed.

**Comment by ericniebler** [comment]
> @ericniebler, what do the constraints on the views' converting constructors buy us, other than potential recursion? Why do we care at all about the properties of the constructor argument beyond the fact that we can turn it into a `Rng`?

Well, the idea is/was to permit this:

```c++
vector<int> v;
auto r = reverse_view{v};
```

... and have that deduce `r` to be `reverse_view<view::all_t<vector<int>>>`. But `all_t<R>` is one of:

* `decay_t<R>`
* `ref_view<remove_reference_t<R>>`
* `subrange<iterator_t<R>, sentinel_t<R>, [sized?]>`

In all cases, there is a conversion from `r` to the destination type, so I think your suggested simplification is OK.

We should try it to be sure.

**Comment by CaseyCarter** [comment]
> Thoughts?

Yes, that had occurred to me. I have a mild preference for "converting constructor template" over "non-template constructor with conversions in the callee" to reduce the number of moves (as detailed in the pull request). Moves are supposed to be cheap, but not moving is cheaper.

**Comment by adah1972** [comment]
Thank you both for the great work!
