### ISSUE TITLE
Can __stl2::ref be a niebloid?

### ISSUE THREAD

**Issue by cjdb** [CaseyCarter/cmcstl2#244]
I don't think anyone outside of cmcstl2 will be using ref, so would it be prudent to transform `__stl2::ref` into  a niebloid and make it `__ref`?

(Similarly for `cref`).

**Comment by CaseyCarter** [comment]
`invoke(_result(_t)?)?`, `reference_wrapper`, and `c?ref` aren't implementation details or extensions: they are polyfills of those components for standard libraries which do not yet implement [P1065](https://wg21.link/p1065) - which currently is *all* standard libraries, since that proposal hasn't yet been approved. P1065 notably does not propose turning `std::c?ref` into a niebloid, so `__stl2::c?ref` shouldn't be a niebloid.
