### ISSUE TITLE
constexpr user-defined addressof operator

### ISSUE THREAD

**Issue by gnzlbg** [CaseyCarter/cmcstl2#27]
I was skimming through the library and was wondering if it is possible to detect an user-defined constexpr addressof operator using the approach followed [here](http://stackoverflow.com/a/15236647/1422197).

**Comment by CaseyCarter** [comment]
I imagine it would be possible, but that's not the use case for `ranges::addressof`. It's not significant whether or not a user-defined address operator is `constexpr`, the point is to avoid calling user-defined address operators altogether.

`std::addressof` can't be portably implemented as `constexpr` since it needs to use `reinterpret_cast`; `ranges::addressof` is `constexpr` when used with types that don't overload `&`. (It is when `STL2_CONSTEXPR_EXT` is defined to `constexpr`, that is. The constexpr-ness of `ranges::__addressof::impl` is independent of compilation modes.)

None of this mess pertains to types which are required to satisfy any of the object concepts, since `Destructible` sensibly forbids `&` to return anything other than the address of the object. We can simply use `&` on them directly and avoid `addressof` and its `constexpr` issues.

Note that `STL2_CONSTEXPR_EXT` isn't well-tested or even applied uniformly throughout the library, thanks to GCC's `constexpr` problems like [PR67376](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67376) that is also the current blockage for `constexpr` in range-v3.

**Comment by gnzlbg** [comment]
> the point is to avoid calling user-defined address operators altogether.

IIUC they are still called through `std::addressof` when the type has an user-defined address operator, e.g., in variant's `get_fn`.  

The way it is right now, if variant is made constexpr, and it store types with a constexpr addressof operator, constexpr get wouldn't work because it would attempt to use `std::addressof`.  

Maybe this case cannot happen for a reason that I'm missing, but I was just wondering about this since IIRC Eggs.Variant also decided to do things this way.

**Comment by CaseyCarter** [comment]
> IIUC they are still called through std::addressof when the type has an user-defined address operator

The entire purpose of `std::addressof` is to get the address of an object regardless of whether it defines an address operator. It can be portably implemented as:

```c++
// Add T's cv-qualifiers to U
template <class T, class U>
struct __xref { using type = U; };
template <class T, class U>
struct __xref<const T> { using type = const U; };
template <class T, class U>
struct __xref<volatile T> { using type = volatile U; };
template <class T, class U>
struct __xref<const volatile T> { using type = const volatile U; };

template <class T>
T* addressof(T& t) noexcept {
  return static_cast<T*>(static_cast<__xref<T,void>*>(
    &reinterpret_cast<__xref<T,char>&>(t)));
}
```

If you *want* to call user-defined address operators, you use `&` instead of `addressof`.

> The way it is right now, if variant is made constexpr, and it store types with a constexpr addressof operator, constexpr get wouldn't work because it would attempt to use `std::addressof`.

Whose variant? range-v3's? My (somewhat sloppy and rushed) variant is as constexpr as I believe is possible - heck, I have constexpr variadic perfect-forwarding `visit` - and nowhere in the implementation does it take the address of an element with either `&` or `addressof`.

**Comment by gnzlbg** [comment]
Thanks for the explanation. I got the whole thing backwards. The only way to get the real address of an object in a constexpr function is if that object doesn't implement an addressof operator at all.
