### ISSUE TITLE
`static_assert` in ostream_iterator.cpp breaks strict-aliasing rules on GCC 7

### ISSUE THREAD

**Issue by cjdb** [CaseyCarter/cmcstl2#99]
Found this while setting up a workshop that uses Ranges with GCC 7.1 when CMAKE_BUILD_TYPE=Release.
Will look into this when I've got a moment.

```
/tmp/cmcstl2/test/iterator/ostream_iterator.cpp: In function 'int main()':
/tmp/cmcstl2/test/iterator/ostream_iterator.cpp:55:29: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  static_assert(noexcept(I{ss}));
                             ^
/tmp/cmcstl2/test/iterator/ostream_iterator.cpp:56:42: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  static_assert(noexcept(I{ss, "some text"}));
```

**Comment by CaseyCarter** [comment]
This is almost certainly [GCC PR 80633 "[7/8 Regression] -Wstrict-aliasing false positive"](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80633) that I reported in range-v3.

**Comment by CaseyCarter** [comment]
FWIW, this doesn't reproduce here (or in range-v3) with today's gcc-7-branch. The problem seems to have been fixed.

Could you try replacing `ss` with `std::declval<std::stringstream&>()` and/or `std::declval<std::ostream&>()` in those two static asserts, and see if your compiler likes either formulation?

**Comment by cjdb** [comment]
> FWIW, this doesn't reproduce here (or in range-v3) with today's gcc-7-branch.

This was compiled with 7.1 release tarball on a Debian-based machine (not sure if it's vanilla).
Interestingly, it passes on the Debug build, which is how I installed it last night.

> Could you try replacing `ss` with `std::declval<std::stringstream&>()` and/or `std::declval<std::ostream&>()` in those two static asserts, and see if your compiler likes either formulation?

Both pass. I get it's a bug, but why does `declval` pass here, when `ss` doesn't?

**Comment by CaseyCarter** [comment]
> This was compiled with 7.1 release tarball on a Debian-based machine (not sure if it's vanilla).
Interestingly, it passes on the Debug build, which is how I installed it last night.

-Wstrict-aliasing only emits warnings when the compiler performs some optimization under the assumption that no aliasing exists.  When the compiler is not optimizing, it doesn't perform the analysis necessary to know there's an issue.

Also, thanks for the reminder. I had forgotten that the warning only manifests when optimizing, and I think I checked with debug builds, so my claim that the bug no longer reproduces is likely wrong.

> Could you try replacing `ss` with `std::declval<std::stringstream&>()` and/or `std::declval<std::ostream&>()` in those two static asserts, and see if your compiler likes either formulation?

> Both pass. I get it's a bug, but why does `declval` pass here, when `ss` doesn't?

I speculate the bug is the alias analysis code doing something silly that doesn't trigger with `declval<foo&>()` because there is no underlying `foo` object to analyze. I stumbled across the `declval` workaround almost by accident while trying to reduce the original bug repro.
